[cmake]
version = "3.15"
cmkr-include = "CMake/cmkr.cmake"

[options]
APPINITHOOK_PRIVATE_MODULES = true
APPINITHOOK_UNLOAD_DISPATCHER = true

[conditions]
private = "APPINITHOOK_PRIVATE_MODULES"
unload-dispatcher = "APPINITHOOK_UNLOAD_DISPATCHER"

[project]
name = "AppInitHook"
version = "0.1.0"
subdirs = ["Libraries", "Modules"]
private.subdirs = ["Private"]
include-before = [
	"CMake/msvc-static-runtime.cmake",
	"CMake/msvc-configurations.cmake",
]
include-after = [
	"CMake/flatten-build-hierarchy.cmake",
	"CMake/AppInitHook-custom.cmake",
]

[target.TestLoader]
type = "executable"
sources = ["TestLoader/*.cpp", "TestLoader/*.hpp"]
