[conditions]
x86 = "CMAKE_SIZEOF_VOID_P EQUAL 4"
x64 = "CMAKE_SIZEOF_VOID_P EQUAL 8"

[target.ntdll]
type = "interface"
include-directories = ["${CMAKE_CURRENT_SOURCE_DIR}"]
link-directories = ["ntdll"]
x86.link-libraries = ["ntdll_x86"]
x64.link-libraries = ["ntdll_x64"]

[target.MinHook]
type = "static"
sources = ["MinHook/**.c", "MinHook/**.h"]
include-directories = ["${CMAKE_CURRENT_SOURCE_DIR}"]

[target.HookDll]
type = "static"
sources = ["HookDll/*.cpp", "HookDll/*.hpp", "ntdll/ntdll.h"]
include-directories = ["HookDll"]
link-libraries = ["ntdll", "MinHook"]

[target.AppInitDispatcher]
type = "shared"
sources = ["AppInitDispatcher/*.cpp", "AppInitDispatcher/*.hpp"]
link-libraries = ["HookDll"]
compile-definitions = ["MODULENAME=\"${CMKR_TARGET}\""]
properties = { EXCLUDE_FROM_DEFAULT_BUILD = "TRUE" }